version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  cluster-tracker:
    image: olipassey/cluster-tracker
    container_name: cluster-tracker
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    volumes:
      - ./conf:/var/www/html/conf

volumes:
  mongodb_data:
